# Generated by Django 5.0.1 on 2025-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_urlshortener_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
